# Generated by Django 3.1.7 on 2021-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0002_articulo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despedida_soltera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Articulo',
            },
        ),
        migrations.CreateModel(
            name='Jugetes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Articulo',
            },
        ),
        migrations.CreateModel(
            name='Lenceria_Hombres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Articulo',
            },
        ),
        migrations.CreateModel(
            name='Lenceria_Mujeres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Articulo',
            },
        ),
        migrations.CreateModel(
            name='Lubricante_cosmeticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Contenido', models.TextField()),
                ('Estado', models.BooleanField()),
                ('imagen', models.ImageField(default='null', upload_to='Article')),
            ],
            options={
                'verbose_name': 'Articulo',
            },
        ),
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Articulo'},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='null', upload_to='Article'),
        ),
    ]
