# Generated by Django 3.1.7 on 2021-03-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0003_auto_20210316_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='despedida_soltera',
            options={'verbose_name': 'Despedida_soltera'},
        ),
        migrations.AlterModelOptions(
            name='jugetes',
            options={'verbose_name': 'Jugete'},
        ),
        migrations.AlterModelOptions(
            name='lenceria_hombres',
            options={'verbose_name': 'Lenceria_Hombre'},
        ),
        migrations.AlterModelOptions(
            name='lenceria_mujeres',
            options={'verbose_name': 'Lenceria_Mujere'},
        ),
        migrations.AlterModelOptions(
            name='lubricante_cosmeticos',
            options={'verbose_name': 'Lubricante_cosmetico'},
        ),
    ]
