# Generated by Django 3.1.7 on 2021-03-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_online', '0004_auto_20210320_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='despedida_soltera',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='jugetes',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='lenceria_hombres',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='lenceria_mujeres',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='lubricante_cosmeticos',
            name='Numero',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
